feat: Record HTTP server request parameters as `message`
applandinc/appmap-python pull request #78
Opened 2021-04-13 22:14 UTC by dustinbyrne

2021-04-15 10:02 UTC, apotterri requested changes
This looks good, except the tests fail for python 3.5. Once that gets sorted out, it'll be good to go.

2021-04-16 10:56 UTC, apotterri submitted a review, later dismissed

2021-04-16 10:58 UTC, apotterri requested changes
Oops, there is one more thing needed here. Can you add a CHANGELOG entry, please?

2021-04-16 13:44 UTC, dividedmind approved these changes
Just one small note, plus missing changelog entry.

2021-04-16 13:44 UTC, dividedmind commented on appmap/test/test_django.py
> +    client.get('/test', { 'my_param': 'example' }, content_type='application/x-www-form-urlencoded')
`GET` requests shouldn't take `content_type` as it relates to body, which GET requests lack.

2021-04-17 09:48 UTC, apotterri commented
Merged here: 2a5be737d7ba8e47782f946c6cb61dd34f147a53

2021-04-17 09:48 UTC, closed without merging